# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
version: "3.8"

networks:
  {{network_name}}:
    driver: bridge
    name: {{network_name}}

volumes:
  vol-db-admin-{{district_id}}:
    driver: local
    name: vol-db-admin-{{district_id}}
  adminapp-bulk-hashcache-{{district_id}}:
    driver: local
    name: vol-adminapp-bulk-hashcache-{{district_id}}
  vol-db-ods-{{district_id}}:
    driver: local
    name: vol-db-ods-{{district_id}}

services:
  db-admin-{{district_id}}:
    image: edfialliance/ods-api-db-admin:${TAG}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      API_MODE: DistrictSpecific
    volumes:
      - vol-db-admin-{{district_id}}:/var/lib/postgresql/data
    restart: always
    container_name: ed-fi-db-admin-{{district_id}}
    networks:
      - {{network_name}}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      start_period: "60s"
      retries: 3

  nginx-{{district_id}}:
    image: edfialliance/ods-api-web-gateway:${TAG}
    environment:
      ADMINAPP_VIRTUAL_NAME: "${ADMINAPP_VIRTUAL_NAME:-adminapp}"
      ODS_VIRTUAL_NAME: "${ODS_VIRTUAL_NAME}"
      DOCS_VIRTUAL_NAME: "${DOCS_VIRTUAL_NAME:-docs}"
    ports:
      - "{{nginx_port}}:443"
    container_name: ed-fi-gateway-{{district_id}}
    restart: always
    hostname: nginx-{{district_id}}
    volumes:
      - ./ssl-certs:/ssl/
    depends_on:
      - api-{{district_id}}
      - adminapp-{{district_id}}
      - swagger-{{district_id}}
    networks:
      - {{network_name}}

  pb-admin-{{district_id}}:
    image: bitnami/pgbouncer
    environment:
      PGBOUNCER_DATABASE: "*"
      PGBOUNCER_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
      PGBOUNCER_EXTRA_FLAGS: "${PGBOUNCER_EXTRA_FLAGS}"
      POSTGRESQL_USER: "${POSTGRES_USER}"
      POSTGRESQL_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRESQL_HOST: db-admin-{{district_id}}
      PGBOUNCER_SET_DATABASE_USER: "yes"
      PGBOUNCER_SET_DATABASE_PASSWORD: "yes"
    restart: always
    container_name: ed-fi-pb-admin-{{district_id}}
    depends_on:
      - db-admin-{{district_id}}
    networks:
      - {{network_name}}

  api-{{district_id}}:
    image: edfialliance/ods-api-web-api:${TAG}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
      ODS_POSTGRES_HOST: edfi_ods_{{district_id}}
      ADMIN_POSTGRES_HOST: pb-admin-{{district_id}}
      API_MODE: DistrictSpecific
      ApiSettings__PathBase: "${ODS_VIRTUAL_NAME}"
      TPDM_ENABLED: "${TPDM_ENABLED:-true}"
      ODS_WAIT_POSTGRES_HOSTS: "{{ods_db}}"
      API_HEALTHCHECK_TEST: "${API_HEALTHCHECK_TEST}"
      NPG_POOLING_ENABLED: "${NPG_POOLING_ENABLED:-false}"
      NPG_API_MAX_POOL_SIZE_ODS: "${NPG_API_MAX_POOL_SIZE_ODS}"
      NPG_API_MAX_POOL_SIZE_ADMIN: "${NPG_API_MAX_POOL_SIZE_ADMIN}"
      NPG_API_MAX_POOL_SIZE_SECURITY: "${NPG_API_MAX_POOL_SIZE_SECURITY}"
      NPG_API_MAX_POOL_SIZE_MASTER: "${NPG_API_MAX_POOL_SIZE_MASTER}"
    volumes:
      - ${LOGS_FOLDER}:/app/logs
    depends_on:
      - pb-admin-{{district_id}}
      - edfi_ods_{{district_id}}
    restart: always
    hostname: api-{{district_id}}
    container_name: ed-fi-ods-api-{{district_id}}
    networks:
      {{network_name}}:
        aliases:
          - api
    healthcheck:
      test: ${API_HEALTHCHECK_TEST}
      start_period: "60s"
      retries: 3

  db-ods-{{district_id}}:
    image: edfialliance/ods-api-db-ods:${TAG}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      TPDM_ENABLED: "${TPDM_ENABLED:-true}"
      ODS_DB: "{{ods_db}}"
    volumes:
      - vol-db-ods-{{district_id}}:/var/lib/postgresql/data
    restart: always
    container_name: ed-fi-db-ods-{{district_id}}
    networks:
      - {{network_name}}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      start_period: "60s"
      retries: 3

  edfi_ods_{{district_id}}:
    image: bitnami/pgbouncer
    environment:
      PGBOUNCER_DATABASE: "*"
      PGBOUNCER_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
      PGBOUNCER_EXTRA_FLAGS: "${PGBOUNCER_EXTRA_FLAGS}"
      POSTGRESQL_USER: "${POSTGRES_USER}"
      POSTGRESQL_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRESQL_HOST: db-ods-{{district_id}}
      PGBOUNCER_SET_DATABASE_USER: "yes"
      PGBOUNCER_SET_DATABASE_PASSWORD: "yes"
    ports:
      - "{{pgbouncer_ods_port}}:${PGBOUNCER_LISTEN_PORT:-6432}"
    restart: always
    container_name: ed-fi-pb-ods-{{district_id}}
    depends_on:
      - db-ods-{{district_id}}
    networks:
      - {{network_name}}

  swagger-{{district_id}}:
    image: edfialliance/ods-api-web-swaggerui:${TAG}
    environment:
      SAMPLE_KEY: "${POPULATED_KEY}"
      SAMPLE_SECRET: "${POPULATED_SECRET}"
      VERSION_URL: "${API_EXTERNAL_URL}"
      WebApiVersionUrl: "${API_EXTERNAL_URL}"
      PathBase: "${DOCS_VIRTUAL_NAME:-docs}"
      SWAGGER_HEALTHCHECK_TEST: "${SWAGGER_HEALTHCHECK_TEST}"
    volumes:
      - ${LOGS_FOLDER}:/app/logs
    depends_on:
      - api-{{district_id}}
    restart: always
    hostname: swagger-{{district_id}}
    container_name: ed-fi-swagger-{{district_id}}
    networks:
      {{network_name}}:
        aliases:
          - docs
    healthcheck:
      test: ${SWAGGER_HEALTHCHECK_TEST}
      start_period: "60s"
      retries: 3

  adminapp-{{district_id}}:
    image: edfialliance/ods-admin-app:${ADMINAPP_TAG}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
      ODS_POSTGRES_HOST: edfi_ods_{{district_id}}
      ADMIN_POSTGRES_HOST: pb-admin-{{district_id}}
      API_MODE: DistrictSpecific
      ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
      ADMINAPP_VIRTUAL_NAME: "${ADMINAPP_VIRTUAL_NAME:-adminapp}"
      API_INTERNAL_URL: "${API_INTERNAL_URL}"
      API_EXTERNAL_URL: "${API_EXTERNAL_URL}"
      ADMINAPP_HEALTHCHECK_TEST: "${ADMINAPP_HEALTHCHECK_TEST}"
      ODS_WAIT_POSTGRES_HOSTS: "{{ods_db}}"
      NPG_POOLING_ENABLED: "${NPG_POOLING_ENABLED:-false}"
      NPG_ADMIN_MAX_POOL_SIZE_ODS: "${NPG_ADMIN_MAX_POOL_SIZE_ODS}"
      NPG_ADMIN_MAX_POOL_SIZE_ADMIN: "${NPG_ADMIN_MAX_POOL_SIZE_ADMIN}"
      NPG_ADMIN_MAX_POOL_SIZE_SECURITY: "${NPG_ADMIN_MAX_POOL_SIZE_SECURITY}"
      ASPNETCORE_PATHBASE: "/adminapp"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "false"
      ASPNETCORE_HTTPS_PORT: "${ASPNETCORE_HTTPS_PORT}"
    volumes:
      - ${LOGS_FOLDER}:/app/logs
      - adminapp-bulk-hashcache-{{district_id}}:/app/BulkUploadHashCache
      - ./ssl-certs:/ssl/
    depends_on:
      - pb-admin-{{district_id}}
      - api-{{district_id}}
      - edfi_ods_{{district_id}}
    restart: always
    hostname: adminapp-{{district_id}}
    container_name: ed-fi-adminapp-{{district_id}}
    networks:
      {{network_name}}:
        aliases:
          - adminapp
    healthcheck:
      test: ${ADMINAPP_HEALTHCHECK_TEST}
      start_period: "60s"
      retries: 3